# Generated by Django 4.0.3 on 2022-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_user', models.TextField(max_length=100)),
                ('event_name', models.TextField(max_length=100)),
                ('event_payload', models.TextField(max_length=10000)),
            ],
        ),
    ]
